import { getPosts } from '../client'
import Head from 'next/head'
import Image from 'next/image'




import Header from '../components/Header'
import Hero from '../components/Hero'
import Cards from '../components/Cards'
import Rexent from '../components/Rexent'
import Recommended from '../components/Recommended'
import Newsletter from '../components/Newsletter'
import Footer from '../components/Footer'

export default function Home({ posts }) {
  
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header/>

      <main>
        <article>
          <Hero/>
          <Cards post={posts}/>
          <Rexent post={posts}/>
          <Recommended post={posts}/>
          <Newsletter/>
        </article>
      </main>

   <Footer/>

    </div>
  )
}


export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts },
  };
}
